### PR TITLE
[Proposal] Keep only latest chart without links

### PR DESCRIPTION
**Pull request by daniel-weisse**
* Keep only the latest version of the chart on main
  * We are not hosting a helm repo here, so keeping old, possibly non functioning charts in our code base seems unnecessary
  * If users want to install an older version, it is still available at the tag of that version
  * We expect users to not manually install the driver, but have it automatically installed and configured by Constellation
* Don't use symlinks to the upstream chart
  * This makes it easier to work with the repo from the oustide (e.g. we can actually curl the files since they are not longer symlinks)

* I have added a packaged chart. IMO we could remove it and require users to clone the repo if they desire to manually install the driver into an existing cluster

### CODE REVIEW

**Comment by derpsteb** [comment]
My main concern with this is that the dogfooding cluster and our public demos are in fact using this as helm repo :D.
If we don't want to treat the repo as such we would need to come up with a different place to host the charts in a way that helm can consume them. Having the charts at different tags of the repo may be helpful for devs wanting to clone them, but is not compatible with helm pull afaik.

Could you explain why we need the files to be curl-able? For downloading the chart to a local dir one can use [helm-pull](https://helm.sh/docs/helm/helm_pull/).

**Comment by daniel-weisse** [comment]
>Could you explain why we need the files to be curl-able

Symlinks are not resolved if you download the file from GitHub.
A symlink file `dir1/file.link` pointing to `dir2/data.txt` downloaded from GitHub will just be a file containing the string `../dir1/data.txt`, this makes it extremely annoying to work with the source files, e.g. when loading them using a `go:generate` script.

>but is not compatible with helm pull afaik

Is this something we want to explicitly support?
Upcoming changes to Constellation will make it unnecessary for users to manually install the CSI driver, additionally it should also remove the need to manually update or manage the charts.

If we want to offer support to manually manage the CSI charts using helm, I would prefer to actually host a helm repo for the CSI charts instead of using a somewhat hacky solution that allows the source repo to be used as a helm repo.

**Comment by derpsteb** [comment]
Thanks for explaining.

After scrolling through the [helm docs](https://helm.sh/docs/topics/chart_repository/) I am a bit unsure what the difference between a "proper" helm repo and our current solution is. Our current solution seems pretty neat(?). We should probably add a CI action to recreate the index automatically, but apart from that seems fine. I am interested to hear concerns. I agree that the link might look a bit rough. :D

Regarding support: We are currently advertising this in the [docs](https://constellation-docs.edgeless.systems/constellation/workflows/storage#installation), so at the very least we should keep the link working imo.
I also feel like this could simplify the [go-generate script](https://github.com/edgelesssys/constellation/pull/532/commits/4904f4fce351f5b2bf6c40bd5a367296de6c965b#diff-48c5cace7df404b83578b116523b3af8501566ab7c0e674c08ec88d5d3f2b8d9) in the constellation repo to sth like:
`helm pull azuredisk-csi-driver --repo https://raw.githubusercontent.com/edgelesssys/constellation-azuredisk-csi-driver/main/charts/edgeless --version v1.0.0 --untar --untardir az-v1.0.0`.

**Comment by daniel-weisse** [comment]
We already have a [helm repo](https://github.com/edgelesssys/helm) for SGX products.
We could do the same for CSI drivers.
Would like a discussion on this first, though

**Comment by derpsteb** [comment]
Summary from discussion call: Daniel merges this change and updates old docs to support new way. In the future we want users to not manually deploy the CSI drivers. Instead a config option will allow enabling/disabling deployment. Possibly a CLI command can deploy CSI drivers if they were disabled during init.

**Review by derpsteb — APPROVED** [review]

**Pull request merged**
